version: '3'

services:
  loki:
    image: grafana/loki:latest
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - ./loki-config:/etc/loki
      - ./wal:/wal

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./logs:/app/logs
      - ./promtail-config:/etc/promtail
    command: -config.file=/etc/promtail/promtail-local-config.yml

  grafana:
    image: grafana/grafana:latest
    container_name: logging_grafana
    restart: unless-stopped
    links:
      - loki:loki
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: '12345'
    ports:
      - '3000:3000'

  loki-demo-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    ports:
      - '3020:3020'
    environment:
      NODE_ENV: development
    volumes:
      - ./logrotate.d:/etc/logrotate.d
      - ./logs:/app/logs
