clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - http://nest-app:3020
        labels:
          job: app-logs
          __path__: /app/logs/*log
