clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: app-logs
          __path__: /app/logs/logs.log
    pipeline_stages:
      - match:
          selector: '{job="contact_now_staging"}'
          stages:
            - drop:
                expression: ELB-HealthChecker\/2.0
                drop_counter_reason: "health check"
